# Generated by Django 4.1.7 on 2023-02-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='value',
            new_name='venue',
        ),
    ]
