# Generated by Django 4.1.7 on 2023-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spurs', '0002_rename_value_match_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.AddField(
            model_name='match',
            name='match',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
