# Generated by Django 4.1.7 on 2023-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spurs', '0003_remove_match_date_remove_match_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
