# Generated by Django 4.1.7 on 2023-02-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spurs', '0004_remove_match_match_match_date_match_team_match_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
    ]
