# Generated by Django 4.1.7 on 2023-02-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spurs', '0005_remove_match_date_remove_match_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
